spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

iron-bank:
  those-who-returns-loans-back: Lannisters

raven:
  where: Braavos, main branch
  enabled: true
